import type { EvidenceResidue } from "@/types/evidence";

export interface ChimeraXCommandSet {
  pdbId: string;
  comparisonPdbId: string | null;
  residues: EvidenceResidue[];
  script: string;
}

function residueSelector(residues: EvidenceResidue[], model: number): string {
  if (residues.length === 0) {
    return "";
  }
  const parts = residues.map((residue) => {
    const chain = residue.chain ? `/${residue.chain}` : "";
    return `#${model}${chain}:${residue.position}`;
  });
  return parts.join(",");
}

/**
 * Build ChimeraX commands from student evidence residues.
 * Never invents residue numbers — empty evidence yields a comment-only script.
 */
export function generateChimeraXCommands(input: {
  pdbId: string;
  comparisonPdbId?: string | null;
  residues: EvidenceResidue[];
}): ChimeraXCommandSet {
  const pdbId = input.pdbId.trim().toUpperCase();
  const comparison = input.comparisonPdbId?.trim().toUpperCase() || null;
  const lines: string[] = [
    "# Generated by Moeller BASIL — residue numbers come from student evidence only.",
    `open ${pdbId}`,
  ];

  if (comparison) {
    lines.push(`open ${comparison}`);
  }

  if (input.residues.length === 0) {
    lines.push(
      "# No evidence residues recorded yet — nothing to select or highlight.",
    );
  } else {
    const sel1 = residueSelector(input.residues, 1);
    lines.push(`select ${sel1}`);
    lines.push("show sel atoms");
    lines.push("style sel stick");
    lines.push("color sel red");
    if (comparison) {
      const sel2 = residueSelector(input.residues, 2);
      lines.push(`select ${sel2}`);
      lines.push("color sel blue");
      lines.push("select #1,#2");
    }
  }

  lines.push("view");

  return {
    pdbId,
    comparisonPdbId: comparison,
    residues: input.residues,
    script: `${lines.join("\n")}\n`,
  };
}
