import { desc, eq } from "drizzle-orm";
import type { AppDatabase } from "@/db/client";
import { evidence, moduleRuns } from "@/db/schema";
import { createId, nowIso } from "@/lib/ids";
import { getProjectById } from "@/lib/db/queries/projects";
import { getModuleRun } from "@/lib/db/queries/moduleRuns";
import { ServiceError } from "@/lib/services/projectService";
import { mapEvidence } from "@/lib/db/mappers";
import { buildProvenance } from "@/lib/provenance/buildProvenance";
import { CURRICULUM_MODULES } from "@/modules/registry";
import type {
  CreateEvidenceInput,
  Evidence,
  EvidenceResidue,
} from "@/types/evidence";

const STRENGTHS = new Set([
  "supporting",
  "strong",
  "conflicting",
  "preliminary",
]);

function validateResidues(residues: EvidenceResidue[]): EvidenceResidue[] {
  if (!Array.isArray(residues) || residues.length === 0) {
    throw new ServiceError(
      "Add at least one residue with a numeric position. The platform will not invent active-site residues.",
      400,
    );
  }
  const cleaned: EvidenceResidue[] = [];
  for (const residue of residues) {
    if (
      typeof residue.position !== "number" ||
      !Number.isInteger(residue.position) ||
      residue.position <= 0
    ) {
      throw new ServiceError(
        "Each residue needs a positive integer position from your evidence — positions are never invented.",
        400,
      );
    }
    cleaned.push({
      chain:
        typeof residue.chain === "string" && residue.chain.trim()
          ? residue.chain.trim().toUpperCase()
          : null,
      position: residue.position,
      aminoAcid:
        typeof residue.aminoAcid === "string" && residue.aminoAcid.trim()
          ? residue.aminoAcid.trim().toUpperCase()
          : null,
      note:
        typeof residue.note === "string" && residue.note.trim()
          ? residue.note.trim()
          : null,
    });
  }
  return cleaned;
}

export async function listEvidenceForProject(
  db: AppDatabase,
  projectId: string,
): Promise<Evidence[]> {
  const project = await getProjectById(db, projectId);
  if (!project) {
    throw new ServiceError("Project not found.", 404);
  }
  const rows = await db
    .select()
    .from(evidence)
    .where(eq(evidence.projectId, projectId))
    .orderBy(desc(evidence.createdAt));
  return rows.map(mapEvidence);
}

/**
 * Student-authored evidence only. Residues must be supplied by the student
 * from prior module observations — never auto-generated by an LLM.
 */
export async function createEvidenceRecord(
  db: AppDatabase,
  projectId: string,
  input: CreateEvidenceInput,
): Promise<Evidence> {
  const project = await getProjectById(db, projectId);
  if (!project) {
    throw new ServiceError("Project not found.", 404);
  }

  const type = input.type?.trim();
  const description = input.description?.trim();
  if (!type) {
    throw new ServiceError("Evidence type is required.", 400);
  }
  if (!description) {
    throw new ServiceError(
      "Describe how the prior module supports these residues.",
      400,
    );
  }

  const sourceModule = CURRICULUM_MODULES.find(
    (module) => module.id === input.sourceModuleId,
  );
  if (!sourceModule) {
    throw new ServiceError("Unknown source module for evidence.", 400);
  }
  if (
    sourceModule.id === "active-site-evidence" ||
    sourceModule.id === "hypothesis-builder" ||
    sourceModule.id === "shannonbot-review" ||
    sourceModule.id === "reports"
  ) {
    throw new ServiceError(
      "Active-site candidates must cite an earlier scientific module (e.g. InterPro, Foldseek, BLAST), not this synthesis step.",
      400,
    );
  }

  const residues = validateResidues(input.residues);
  const strength =
    input.strength && STRENGTHS.has(input.strength) ? input.strength : null;

  const timestamp = nowIso();
  const id = createId();
  const provenance = buildProvenance({
    tool: "student_evidence",
    source: "student_observation",
    parameters: {
      sourceModuleId: sourceModule.id,
      sourceModuleName: sourceModule.name,
      residueCount: residues.length,
    },
    version: "phase5",
  });

  await db.insert(evidence).values({
    id,
    projectId,
    type,
    description,
    sourceResultId: input.sourceResultId ?? null,
    sourceModuleId: sourceModule.id,
    residuesJson: JSON.stringify(residues),
    strength,
    provenanceJson: JSON.stringify(provenance),
    isDemo: project.isDemo,
    createdAt: timestamp,
  });

  const run = await getModuleRun(db, projectId, "active-site-evidence");
  if (run && run.status !== "complete") {
    await db
      .update(moduleRuns)
      .set({
        status: "in_progress",
        startedAt: run.startedAt ?? timestamp,
        error: null,
        updatedAt: timestamp,
      })
      .where(eq(moduleRuns.id, run.id));
  }

  const rows = await db.select().from(evidence).where(eq(evidence.id, id)).limit(1);
  return mapEvidence(rows[0]);
}

export async function deleteEvidenceRecord(
  db: AppDatabase,
  projectId: string,
  evidenceId: string,
): Promise<void> {
  const rows = await db
    .select()
    .from(evidence)
    .where(eq(evidence.id, evidenceId))
    .limit(1);
  if (rows.length === 0 || rows[0].projectId !== projectId) {
    throw new ServiceError("Evidence record not found.", 404);
  }
  await db.delete(evidence).where(eq(evidence.id, evidenceId));
}

export async function completeActiveSiteModule(
  db: AppDatabase,
  projectId: string,
): Promise<{ runId: string; status: string }> {
  const items = await listEvidenceForProject(db, projectId);
  if (items.length === 0) {
    throw new ServiceError(
      "Record at least one evidence-backed residue before completing Active-Site Evidence Synthesis. Residues are never invented automatically.",
      400,
    );
  }
  const run = await getModuleRun(db, projectId, "active-site-evidence");
  if (!run) {
    throw new ServiceError("Active-site module run is missing.", 500);
  }
  const timestamp = nowIso();
  await db
    .update(moduleRuns)
    .set({
      status: "complete",
      completedAt: timestamp,
      startedAt: run.startedAt ?? timestamp,
      error: null,
      updatedAt: timestamp,
    })
    .where(eq(moduleRuns.id, run.id));
  return { runId: run.id, status: "complete" };
}

export function collectUniqueResidues(items: Evidence[]): EvidenceResidue[] {
  const seen = new Set<string>();
  const out: EvidenceResidue[] = [];
  for (const item of items) {
    for (const residue of item.residues ?? []) {
      const key = `${residue.chain ?? ""}:${residue.position}`;
      if (seen.has(key)) {
        continue;
      }
      seen.add(key);
      out.push(residue);
    }
  }
  return out.sort((a, b) => a.position - b.position);
}

